import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-6 py-12 max-w-4xl">
        {/* Back Navigation */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-muted hover:text-foreground transition-colors mb-12"
        >
          <ArrowLeft size={20} />
          Back to home
        </Link>

        {/* Content */}
        <div className="prose prose-invert max-w-none">
          <h1 className="text-5xl font-light mb-8">Privacy Policy</h1>
          
          <p className="text-muted mb-12">
            Last updated: {new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}
          </p>

          <div className="bg-surface border border-border rounded-2xl p-8 mb-12">
            <h2 className="text-3xl font-light mb-4">Our Privacy Promise</h2>
            <p className="text-xl text-muted leading-relaxed">
              Eris is built on a foundation of privacy. Your conversations never leave your device. 
              We don't collect data because we can't — everything runs locally on your iPhone or iPad.
            </p>
          </div>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">1. No Data Collection</h2>
            <p className="text-muted leading-relaxed">
              We want to be absolutely clear: <strong className="text-white">Eris does not collect any data</strong>. 
              This includes but is not limited to:
            </p>
            <ul className="list-disc list-inside text-muted space-y-2 mt-4">
              <li>Conversations with AI models</li>
              <li>Personal information</li>
              <li>Usage statistics</li>
              <li>Device information</li>
              <li>Location data</li>
              <li>Analytics or telemetry</li>
              <li>Crash reports</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">2. Local Storage Only</h2>
            <p className="text-muted leading-relaxed">
              All data generated by Eris is stored locally on your device using Apple's SwiftData framework. 
              This includes:
            </p>
            <ul className="list-disc list-inside text-muted space-y-2 mt-4">
              <li>Chat conversations and history</li>
              <li>Downloaded AI models</li>
              <li>App preferences and settings</li>
            </ul>
            <p className="text-muted leading-relaxed mt-4">
              You have complete control over this data. You can delete individual conversations, remove models, 
              or clear all app data at any time through the app's settings.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">3. Network Usage</h2>
            <p className="text-muted leading-relaxed">
              Eris requires internet connection only for:
            </p>
            <ul className="list-disc list-inside text-muted space-y-2 mt-4">
              <li>Initial download of AI models from Hugging Face</li>
              <li>Checking for app updates through the App Store</li>
            </ul>
            <p className="text-muted leading-relaxed mt-4">
              Once models are downloaded, Eris works completely offline. No conversation data is ever transmitted 
              over the network.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">4. Third-Party Services</h2>
            <p className="text-muted leading-relaxed">
              Eris uses AI models hosted on Hugging Face for initial download only. These downloads are subject 
              to Hugging Face's privacy policy. However, once downloaded, the models run entirely on your device 
              with no external connections.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">5. iOS Permissions</h2>
            <p className="text-muted leading-relaxed">
              Eris may request the following iOS permissions:
            </p>
            <ul className="list-disc list-inside text-muted space-y-2 mt-4">
              <li><strong className="text-white">Network Access:</strong> Only for downloading AI models</li>
              <li><strong className="text-white">Storage:</strong> To save models and conversations locally</li>
            </ul>
            <p className="text-muted leading-relaxed mt-4">
              No other permissions are requested or required.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">6. Data Security</h2>
            <p className="text-muted leading-relaxed">
              Your data security relies on iOS's built-in security features:
            </p>
            <ul className="list-disc list-inside text-muted space-y-2 mt-4">
              <li>Data is encrypted on your device using iOS encryption</li>
              <li>App sandboxing prevents other apps from accessing Eris data</li>
              <li>Face ID/Touch ID can be used to secure your device</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">7. Children's Privacy</h2>
            <p className="text-muted leading-relaxed">
              Since Eris doesn't collect any data, it's safe for users of all ages. We don't collect information 
              from anyone, including children under 13.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">8. Open Source Transparency</h2>
            <p className="text-muted leading-relaxed">
              Eris is open source. You can verify our privacy claims by reviewing our code on GitHub. 
              Transparency is key to trust, and we believe you should be able to see exactly how your data is handled.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">9. Changes to This Policy</h2>
            <p className="text-muted leading-relaxed">
              We may update this Privacy Policy from time to time. We will notify you of any changes by updating 
              the "Last updated" date at the top of this policy.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-light mb-4">10. Contact Us</h2>
            <p className="text-muted leading-relaxed">
              If you have any questions about this Privacy Policy or our privacy practices, please contact us at:
            </p>
            <p className="text-muted mt-4">
              <a 
                href="mailto:contact@northernbytes.dev"
                className="text-white underline hover:text-muted transition-colors"
              >
                contact@northernbytes.dev
              </a>
            </p>
          </section>

          <div className="bg-surface border border-border rounded-2xl p-8 mt-16">
            <p className="text-center text-muted">
              Remember: Your privacy isn't just a feature — it's our foundation.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}